// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDAIRHctA2pjUGFnKv9eqMw5OUDhRqKI',
    appId: '1:1017658897245:web:b19b97527ff1b71aa32eb4',
    messagingSenderId: '1017658897245',
    projectId: 'order-picker-bf126',
    authDomain: 'order-picker-bf126.firebaseapp.com',
    storageBucket: 'order-picker-bf126.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEphfSGmT5y6U-G4230ZEjOvZ14mB_ZoE',
    appId: '1:1017658897245:android:d051f93509c65971a32eb4',
    messagingSenderId: '1017658897245',
    projectId: 'order-picker-bf126',
    storageBucket: 'order-picker-bf126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoyu8B13mGrU2t2DjNEiOvJJomJ2etJ00',
    appId: '1:1017658897245:ios:2cb79eb6b80be066a32eb4',
    messagingSenderId: '1017658897245',
    projectId: 'order-picker-bf126',
    storageBucket: 'order-picker-bf126.appspot.com',
    iosBundleId: 'com.example.orderPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoyu8B13mGrU2t2DjNEiOvJJomJ2etJ00',
    appId: '1:1017658897245:ios:c791046980fbf3e7a32eb4',
    messagingSenderId: '1017658897245',
    projectId: 'order-picker-bf126',
    storageBucket: 'order-picker-bf126.appspot.com',
    iosBundleId: 'com.example.orderPicker.RunnerTests',
  );
}
